export type Artist = {
  id: string;
  username: string;
  name: string;
  role: string;
  category: string;
  tags: string[];
  city: string;
  state: string;
  country: string;
  from: string;
  bio: string;
  image: string;
  banner: string;
  verified: boolean;
  featured: boolean;
  links: {
    instagram?: string;
    spotify?: string;
    youtube?: string;
    website?: string;
    soundcloud?: string;
    behance?: string;
    tiktok?: string;
  };
  workSamples: { src: string; alt: string }[];
  joinedAt: string;
};

export type Category = {
  slug: string;
  label: string;
  count: number;
  description: string;
};

export type Conversation = {
  id: string;
  with: string;
  lastMessage: string;
  lastMessageAt: string;
  unread: boolean;
  messages: Message[];
};

export type Message = {
  id: string;
  from: "me" | "them";
  text: string;
  sentAt: string;
};

export const CATEGORIES: Category[] = [
  { slug: "producers", label: "Producers", count: 47, description: "Beat makers, music producers, and audio engineers" },
  { slug: "graphic-designers", label: "Graphic Designers", count: 38, description: "Brand identity, digital design, and visual communication" },
  { slug: "photographers", label: "Photographers", count: 52, description: "Portrait, event, product, and fine art photography" },
  { slug: "videographers", label: "Videographers", count: 29, description: "Music videos, short films, and cinematic content" },
  { slug: "singers", label: "Singers", count: 61, description: "Vocalists, worship singers, and recording artists" },
  { slug: "songwriters", label: "Songwriters", count: 34, description: "Lyricists, composers, and topliner writers" },
  { slug: "musicians", label: "Musicians", count: 43, description: "Instrumentalists, session players, and band members" },
  { slug: "worship-leaders", label: "Worship Leaders", count: 27, description: "Leading worship in churches, events, and gatherings" },
  { slug: "visual-artists", label: "Visual Artists", count: 22, description: "Painters, illustrators, and mixed media artists" },
  { slug: "content-creators", label: "Content Creators", count: 35, description: "Social media, podcasts, and digital storytelling" },
  { slug: "creative-directors", label: "Creative Directors", count: 18, description: "Vision casting, branding, and creative strategy" },
  { slug: "filmmakers", label: "Filmmakers", count: 24, description: "Documentary, narrative, and experimental film" },
];

export const MOCK_ARTISTS: Artist[] = [
  {
    id: "1",
    username: "avamorales",
    name: "Ava Morales",
    role: "Vocalist & Songwriter",
    category: "singers",
    tags: ["Worship", "R&B", "Gospel"],
    city: "Los Angeles",
    state: "CA",
    country: "US",
    from: "Houston, TX",
    bio: "Singer-songwriter crafting worship music that bridges contemporary R&B with gospel roots. Passionate about creating spaces where people encounter God through authentic, soul-stirring melodies. Currently working on my debut EP and leading worship at Mosaic Church LA.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&h=400&fit=crop",
    verified: true,
    featured: true,
    links: {
      instagram: "avamoralesmusic",
      spotify: "avamorales",
      youtube: "AvaMoralesMusic",
      website: "avamorales.com",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop", alt: "Live performance" },
      { src: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&h=400&fit=crop", alt: "Studio session" },
      { src: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&h=400&fit=crop", alt: "Worship night" },
    ],
    joinedAt: "2024-01-15",
  },
  {
    id: "2",
    username: "elijahosei",
    name: "Elijah Osei",
    role: "Producer & Worship Leader",
    category: "producers",
    tags: ["Gospel", "Neo-Soul", "Worship"],
    city: "Atlanta",
    state: "GA",
    country: "US",
    from: "Accra, Ghana",
    bio: "Bridging Afrobeat rhythms with worship music. Grammy-considered producer with over 200 placements across gospel and contemporary Christian music. I believe the sound of Heaven has no genre walls.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=1200&h=400&fit=crop",
    verified: true,
    featured: true,
    links: {
      instagram: "elijahosei",
      spotify: "elijahoseimusic",
      youtube: "ElijahOsei",
      soundcloud: "elijahosei",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&h=400&fit=crop", alt: "Studio setup" },
      { src: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=600&h=400&fit=crop", alt: "Live production" },
    ],
    joinedAt: "2024-02-03",
  },
  {
    id: "3",
    username: "selahkim",
    name: "Selah Kim",
    role: "Creative Director & Designer",
    category: "creative-directors",
    tags: ["Branding", "Art Direction", "Typography"],
    city: "New York",
    state: "NY",
    country: "US",
    from: "Seoul, South Korea",
    bio: "Building brand identities for Kingdom-minded organizations and artists. Former lead designer at Hillsong Creative. I specialize in visual storytelling that feels elevated and intentional.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&h=400&fit=crop",
    verified: true,
    featured: true,
    links: {
      instagram: "selahkim.design",
      website: "selahkim.co",
      behance: "selahkim",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop", alt: "Brand identity project" },
      { src: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&h=400&fit=crop", alt: "Editorial design" },
      { src: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&h=400&fit=crop", alt: "Typography work" },
    ],
    joinedAt: "2024-01-20",
  },
  {
    id: "4",
    username: "micahtorres",
    name: "Micah Torres",
    role: "Filmmaker & Photographer",
    category: "filmmakers",
    tags: ["Documentary", "Music Videos", "Cinematic"],
    city: "Nashville",
    state: "TN",
    country: "US",
    from: "Miami, FL",
    bio: "Cinematic storyteller documenting the intersection of faith and art. My lens is drawn to the raw, unfiltered moments where God shows up. Directed music videos for Maverick City, Bethel, and independent Kingdom artists.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "micahtorresfilm",
      youtube: "MicahTorresFilm",
      website: "micahtorres.film",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&h=400&fit=crop", alt: "Film set" },
      { src: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&h=400&fit=crop", alt: "Behind the scenes" },
    ],
    joinedAt: "2024-03-10",
  },
  {
    id: "5",
    username: "zionadeyemi",
    name: "Zion Adeyemi",
    role: "Graphic Designer",
    category: "graphic-designers",
    tags: ["Album Art", "Social Media", "Illustration"],
    city: "London",
    state: "",
    country: "UK",
    from: "Lagos, Nigeria",
    bio: "Visual designer creating album artwork, social media content, and illustrations for Christian artists and ministries worldwide. My work blends contemporary design with cultural storytelling rooted in African heritage.",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "zionadeyemi",
      behance: "zionadeyemi",
      website: "zionadeyemi.design",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop", alt: "Album artwork" },
      { src: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=600&h=400&fit=crop", alt: "Poster design" },
    ],
    joinedAt: "2024-02-18",
  },
  {
    id: "6",
    username: "gracenhema",
    name: "Grace Nhema",
    role: "Photographer",
    category: "photographers",
    tags: ["Portraits", "Events", "Editorial"],
    city: "Dallas",
    state: "TX",
    country: "US",
    from: "Harare, Zimbabwe",
    bio: "Portrait and event photographer with a gift for capturing light and emotion. I shoot worship nights, church events, artist headshots, and creative editorial work. Every frame is an offering.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=400&fit=crop",
    verified: true,
    featured: true,
    links: {
      instagram: "gracenhema",
      website: "gracenhemaphoto.com",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop", alt: "Mountain landscape" },
      { src: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&h=400&fit=crop", alt: "Nature editorial" },
      { src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=400&fit=crop", alt: "Golden hour shoot" },
    ],
    joinedAt: "2024-04-05",
  },
  {
    id: "7",
    username: "josiahdavis",
    name: "Josiah Davis",
    role: "Worship Leader & Musician",
    category: "worship-leaders",
    tags: ["Worship", "Keys", "Songwriting"],
    city: "Chicago",
    state: "IL",
    country: "US",
    from: "Detroit, MI",
    bio: "Leading worship at Harvest Bible Chapel and writing songs for the local church. Multi-instrumentalist (keys, guitar, bass) with a heart for creating environments where people can encounter God authentically.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&h=400&fit=crop",
    verified: false,
    featured: false,
    links: {
      instagram: "josiahdavisworship",
      spotify: "josiahdavis",
      youtube: "JosiahDavisMusic",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&h=400&fit=crop", alt: "Worship leading" },
    ],
    joinedAt: "2024-05-12",
  },
  {
    id: "8",
    username: "naomipatel",
    name: "Naomi Patel",
    role: "Content Creator & Writer",
    category: "content-creators",
    tags: ["Devotionals", "Social Media", "Podcasting"],
    city: "Austin",
    state: "TX",
    country: "US",
    from: "Mumbai, India",
    bio: "Digital storyteller creating faith-based content that resonates with the next generation. Host of the 'Set Apart Creative' podcast with 50K+ monthly listeners. I believe in the power of intentional, Kingdom-minded media.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "naomipatel",
      youtube: "NaomiPatelCreates",
      tiktok: "naomipatel",
      website: "naomipatel.co",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=400&fit=crop", alt: "Content creation" },
      { src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop", alt: "Podcast recording" },
    ],
    joinedAt: "2024-03-28",
  },
  {
    id: "9",
    username: "isaiahcarter",
    name: "Isaiah Carter",
    role: "Producer & Audio Engineer",
    category: "producers",
    tags: ["Hip-Hop", "Gospel", "Mixing"],
    city: "Memphis",
    state: "TN",
    country: "US",
    from: "Memphis, TN",
    bio: "Grammy-nominated producer and mix engineer bringing Kingdom sound to mainstream quality. Credits include Kirk Franklin, Lecrae, and Social Club Misfits. My studio is a sanctuary for artists who want excellence without compromise.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=1200&h=400&fit=crop",
    verified: true,
    featured: true,
    links: {
      instagram: "isaiahcarterbeats",
      spotify: "isaiahcarter",
      soundcloud: "isaiahcarter",
      website: "isaiahcarter.studio",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&h=400&fit=crop", alt: "Studio" },
      { src: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=600&h=400&fit=crop", alt: "Mixing session" },
    ],
    joinedAt: "2024-01-08",
  },
  {
    id: "10",
    username: "maraluna",
    name: "Mara Luna",
    role: "Visual Artist & Painter",
    category: "visual-artists",
    tags: ["Oil Painting", "Murals", "Prophetic Art"],
    city: "San Diego",
    state: "CA",
    country: "US",
    from: "Mexico City, Mexico",
    bio: "Creating prophetic art and large-scale murals that visualize the beauty of the Kingdom. My paintings explore themes of identity, belonging, and divine encounter through rich color and texture.",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&h=400&fit=crop",
    verified: false,
    featured: false,
    links: {
      instagram: "maraluna.art",
      website: "maralunaart.com",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop", alt: "Oil painting" },
      { src: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&h=400&fit=crop", alt: "Mural work" },
    ],
    joinedAt: "2024-06-01",
  },
  {
    id: "11",
    username: "danielwright",
    name: "Daniel Wright",
    role: "Videographer & Editor",
    category: "videographers",
    tags: ["Music Videos", "Church Media", "Commercials"],
    city: "Portland",
    state: "OR",
    country: "US",
    from: "Portland, OR",
    bio: "Cinematic videographer and editor specializing in music videos and church content. I bring a film-quality approach to every project because Kingdom work deserves Kingdom excellence.",
    image: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "danielwrightfilm",
      youtube: "DanielWrightFilm",
      website: "danielwright.video",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&h=400&fit=crop", alt: "Video production" },
      { src: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&h=400&fit=crop", alt: "Camera setup" },
    ],
    joinedAt: "2024-04-20",
  },
  {
    id: "12",
    username: "estheromah",
    name: "Esther Omah",
    role: "Singer & Worship Artist",
    category: "singers",
    tags: ["Afro-Gospel", "Worship", "Contemporary"],
    city: "Houston",
    state: "TX",
    country: "US",
    from: "Lagos, Nigeria",
    bio: "Nigerian-American worship artist blending Afro-Gospel sounds with contemporary praise. Signed to Integrity Music. My prayer is that every song I write carries people into the presence of God.",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&h=400&fit=crop",
    verified: true,
    featured: true,
    links: {
      instagram: "estheromah",
      spotify: "estheromah",
      youtube: "EstherOmahOfficial",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop", alt: "Live worship" },
      { src: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&h=400&fit=crop", alt: "Recording" },
    ],
    joinedAt: "2024-02-14",
  },
  {
    id: "13",
    username: "lukehavens",
    name: "Luke Havens",
    role: "Songwriter & Musician",
    category: "songwriters",
    tags: ["Acoustic", "Folk Worship", "Hymns"],
    city: "Franklin",
    state: "TN",
    country: "US",
    from: "Nashville, TN",
    bio: "Writing modern hymns and acoustic worship songs from a farmhouse outside Nashville. Cuts with Chris Tomlin, Pat Barrett, and Housefires. I write from silence, solitude, and scripture.",
    image: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "lukehavens",
      spotify: "lukehavensmusic",
      website: "lukehavens.com",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&h=400&fit=crop", alt: "Acoustic session" },
    ],
    joinedAt: "2024-03-05",
  },
  {
    id: "14",
    username: "riyajames",
    name: "Riya James",
    role: "Photographer & Creative",
    category: "photographers",
    tags: ["Weddings", "Lifestyle", "Brand"],
    city: "San Francisco",
    state: "CA",
    country: "US",
    from: "Bangalore, India",
    bio: "Capturing authentic moments through a lens of grace. Specializing in weddings, lifestyle portraits, and brand photography for Kingdom entrepreneurs and ministries. Light chaser. Story keeper.",
    image: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=400&fit=crop",
    verified: false,
    featured: false,
    links: {
      instagram: "riyajamesphoto",
      website: "riyajames.com",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=400&fit=crop", alt: "Wedding shoot" },
      { src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=400&fit=crop", alt: "Golden hour" },
    ],
    joinedAt: "2024-05-30",
  },
  {
    id: "15",
    username: "marcusblake",
    name: "Marcus Blake",
    role: "Musician & Keys Player",
    category: "musicians",
    tags: ["Keys", "Jazz", "Session"],
    city: "New Orleans",
    state: "LA",
    country: "US",
    from: "New Orleans, LA",
    bio: "Session keyboardist and musical director blending jazz, gospel, and neo-soul. Currently MD for Tasha Cobbs Leonard. I believe musicianship is ministry, and every chord is a prayer.",
    image: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "marcusblakekeys",
      spotify: "marcusblake",
      youtube: "MarcusBlakeMusic",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&h=400&fit=crop", alt: "Piano performance" },
    ],
    joinedAt: "2024-04-12",
  },
  {
    id: "16",
    username: "tamikaross",
    name: "Tamika Ross",
    role: "Graphic Designer",
    category: "graphic-designers",
    tags: ["Church Graphics", "Motion Design", "Social"],
    city: "Charlotte",
    state: "NC",
    country: "US",
    from: "Charlotte, NC",
    bio: "Designing sermon series graphics, social media content, and motion graphics for churches and ministries. Making the local church look as excellent as the message it carries.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&h=400&fit=crop",
    verified: false,
    featured: false,
    links: {
      instagram: "tamikarossdesign",
      behance: "tamikaross",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&h=400&fit=crop", alt: "Design work" },
      { src: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&h=400&fit=crop", alt: "Social content" },
    ],
    joinedAt: "2024-06-15",
  },
  {
    id: "17",
    username: "samuelpark",
    name: "Samuel Park",
    role: "Filmmaker & Director",
    category: "filmmakers",
    tags: ["Short Films", "Narrative", "Church Films"],
    city: "Toronto",
    state: "ON",
    country: "CA",
    from: "Seoul, South Korea",
    bio: "Narrative filmmaker exploring themes of redemption, identity, and grace through cinematic storytelling. Sundance Lab fellow. My films are love letters to the God who makes all things new.",
    image: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "samuelparkfilm",
      youtube: "SamuelParkDirector",
      website: "samuelpark.film",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&h=400&fit=crop", alt: "Film still" },
    ],
    joinedAt: "2024-03-22",
  },
  {
    id: "18",
    username: "oliviastone",
    name: "Olivia Stone",
    role: "Content Creator & Podcaster",
    category: "content-creators",
    tags: ["Podcast", "YouTube", "Writing"],
    city: "Denver",
    state: "CO",
    country: "US",
    from: "Minneapolis, MN",
    bio: "Host of 'The Refined Creative' podcast — conversations with Kingdom artists about faith, craft, and calling. 100K+ YouTube subscribers. I help creatives find their voice and build with purpose.",
    image: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=400&fit=crop&crop=faces",
    banner: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&h=400&fit=crop",
    verified: true,
    featured: false,
    links: {
      instagram: "oliviastonecreates",
      youtube: "OliviaStoneCreates",
      tiktok: "oliviastone",
      website: "therefinedcreative.com",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop", alt: "Podcast recording" },
      { src: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=400&fit=crop", alt: "Writing" },
    ],
    joinedAt: "2024-02-28",
  },
  {
    id: "19",
    username: "andrewchen",
    name: "Andrew Chen",
    role: "Worship Leader & Songwriter",
    category: "worship-leaders",
    tags: ["Worship", "Songwriting", "Guitar"],
    city: "Seattle",
    state: "WA",
    country: "US",
    from: "Vancouver, BC",
    bio: "Worship pastor at The City Church Seattle. Writing songs for the global church with a Pacific Northwest sensibility — intimate, spacious, and rooted in scripture. Guitar-first worship.",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=400&fit=crop",
    verified: false,
    featured: false,
    links: {
      instagram: "andrewchenworship",
      spotify: "andrewchen",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop", alt: "Worship set" },
    ],
    joinedAt: "2024-05-18",
  },
  {
    id: "20",
    username: "danijelovic",
    name: "Dani Jelovic",
    role: "Visual Artist & Illustrator",
    category: "visual-artists",
    tags: ["Illustration", "Digital Art", "Murals"],
    city: "Miami",
    state: "FL",
    country: "US",
    from: "Zagreb, Croatia",
    bio: "Creating vibrant illustrations and murals that tell stories of faith, hope, and restoration. My art is a visual conversation between the seen and unseen realms. Currently painting a 40-foot mural at Vous Church Miami.",
    image: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&h=400&fit=crop",
    verified: false,
    featured: false,
    links: {
      instagram: "danijelovic.art",
      website: "danijelovic.com",
    },
    workSamples: [
      { src: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop", alt: "Artwork" },
      { src: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&h=400&fit=crop", alt: "Mural" },
    ],
    joinedAt: "2024-06-08",
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    with: "selahkim",
    lastMessage: "I'd love to collaborate on the album artwork — let's set up a call this week?",
    lastMessageAt: "2025-05-25T14:30:00Z",
    unread: true,
    messages: [
      { id: "m1", from: "me", text: "Hey Selah! I've been following your work and love the branding you did for Hillsong Creative. I'm working on my debut EP and looking for a designer.", sentAt: "2025-05-24T10:00:00Z" },
      { id: "m2", from: "them", text: "Thanks so much! I checked out your music — your sound is incredible. I'd definitely be interested in working together on the visual identity.", sentAt: "2025-05-24T11:15:00Z" },
      { id: "m3", from: "me", text: "That means a lot. I'm going for something warm and cinematic — earthy tones, analog textures. Think Bon Iver meets gospel.", sentAt: "2025-05-24T14:30:00Z" },
      { id: "m4", from: "them", text: "Oh I love that direction. I've been working on a lot of organic, textured designs lately. Let me pull together some references.", sentAt: "2025-05-24T15:45:00Z" },
      { id: "m5", from: "them", text: "I'd love to collaborate on the album artwork — let's set up a call this week?", sentAt: "2025-05-25T14:30:00Z" },
    ],
  },
  {
    id: "conv-2",
    with: "micahtorres",
    lastMessage: "The rough cut looks amazing. Let me know when you want notes.",
    lastMessageAt: "2025-05-24T18:00:00Z",
    unread: false,
    messages: [
      { id: "m6", from: "them", text: "Hey! I saw you're based in LA — I'm shooting a music video there next month for an independent artist. Would you want to be part of it?", sentAt: "2025-05-22T09:00:00Z" },
      { id: "m7", from: "me", text: "Definitely interested! What's the concept?", sentAt: "2025-05-22T10:30:00Z" },
      { id: "m8", from: "them", text: "It's a worship visual — outdoor, golden hour, very organic and cinematic. I think your voice would be perfect for the feature.", sentAt: "2025-05-22T12:00:00Z" },
      { id: "m9", from: "me", text: "The rough cut looks amazing. Let me know when you want notes.", sentAt: "2025-05-24T18:00:00Z" },
    ],
  },
  {
    id: "conv-3",
    with: "isaiahcarter",
    lastMessage: "Sent you the stems. Check your email!",
    lastMessageAt: "2025-05-23T20:15:00Z",
    unread: false,
    messages: [
      { id: "m10", from: "them", text: "Yo! Heard your demo through a mutual friend. The production quality is next level. Who produced it?", sentAt: "2025-05-20T16:00:00Z" },
      { id: "m11", from: "me", text: "Thanks Isaiah! I actually self-produced most of it but I'm looking for someone to mix and master the final versions.", sentAt: "2025-05-20T17:30:00Z" },
      { id: "m12", from: "them", text: "I'd be honored to work on that. Send me a couple tracks and I'll do a test mix — no charge. Just want to hear what we can create together.", sentAt: "2025-05-21T09:00:00Z" },
      { id: "m13", from: "me", text: "Sent you the stems. Check your email!", sentAt: "2025-05-23T20:15:00Z" },
    ],
  },
  {
    id: "conv-4",
    with: "gracenhema",
    lastMessage: "Those headshots turned out incredible. Thank you! 🙏",
    lastMessageAt: "2025-05-22T11:00:00Z",
    unread: false,
    messages: [
      { id: "m14", from: "me", text: "Hi Grace! I need new artist headshots and press photos for my upcoming release. Are you available next week?", sentAt: "2025-05-19T14:00:00Z" },
      { id: "m15", from: "them", text: "Yes! I have availability on Tuesday and Thursday. Golden hour shoots are my favorite — would you be down for an outdoor session?", sentAt: "2025-05-19T16:00:00Z" },
      { id: "m16", from: "me", text: "Those headshots turned out incredible. Thank you! 🙏", sentAt: "2025-05-22T11:00:00Z" },
    ],
  },
];

export const CURRENT_USER: Artist = {
  id: "current",
  username: "avamorales",
  name: "Ava Morales",
  role: "Vocalist & Songwriter",
  category: "singers",
  tags: ["Worship", "R&B", "Gospel"],
  city: "Los Angeles",
  state: "CA",
  country: "US",
  from: "Houston, TX",
  bio: "Singer-songwriter crafting worship music that bridges contemporary R&B with gospel roots. Passionate about creating spaces where people encounter God through authentic, soul-stirring melodies.",
  image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
  banner: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&h=400&fit=crop",
  verified: true,
  featured: true,
  links: {
    instagram: "avamoralesmusic",
    spotify: "avamorales",
    youtube: "AvaMoralesMusic",
    website: "avamorales.com",
  },
  workSamples: [
    { src: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop", alt: "Live performance" },
    { src: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&h=400&fit=crop", alt: "Studio session" },
    { src: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&h=400&fit=crop", alt: "Worship night" },
  ],
  joinedAt: "2024-01-15",
};
